// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.2
// source: employee/employee.proto

package employee

import (
	comm "./comm"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Employee_Deliver_FullMethodName                       = "/employee.Employee/deliver"
	Employee_Browses_FullMethodName                       = "/employee.Employee/browses"
	Employee_DeliverRecords_FullMethodName                = "/employee.Employee/deliverRecords"
	Employee_CompleteSelfInformation_FullMethodName       = "/employee.Employee/completeSelfInformation"
	Employee_FindEmployeeInformation_FullMethodName       = "/employee.Employee/findEmployeeInformation"
	Employee_FindEmployeeSimpleInformation_FullMethodName = "/employee.Employee/findEmployeeSimpleInformation"
)

// EmployeeClient is the client API for Employee service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmployeeClient interface {
	Deliver(ctx context.Context, in *OperateRequest, opts ...grpc.CallOption) (*OperateResponse, error)
	Browses(ctx context.Context, in *OperateRequest, opts ...grpc.CallOption) (*OperateResponse, error)
	DeliverRecords(ctx context.Context, in *FindRecordsReq, opts ...grpc.CallOption) (*OperateResponse, error)
	CompleteSelfInformation(ctx context.Context, in *SelfInformation, opts ...grpc.CallOption) (*comm.ResponseHeader, error)
	FindEmployeeInformation(ctx context.Context, in *FindEmployeeInfoReq, opts ...grpc.CallOption) (*FindEmployeeResponse, error)
	FindEmployeeSimpleInformation(ctx context.Context, in *SplitPage, opts ...grpc.CallOption) (*FindEmployeeSimpleResponse, error)
}

type employeeClient struct {
	cc grpc.ClientConnInterface
}

func NewEmployeeClient(cc grpc.ClientConnInterface) EmployeeClient {
	return &employeeClient{cc}
}

func (c *employeeClient) Deliver(ctx context.Context, in *OperateRequest, opts ...grpc.CallOption) (*OperateResponse, error) {
	out := new(OperateResponse)
	err := c.cc.Invoke(ctx, Employee_Deliver_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeClient) Browses(ctx context.Context, in *OperateRequest, opts ...grpc.CallOption) (*OperateResponse, error) {
	out := new(OperateResponse)
	err := c.cc.Invoke(ctx, Employee_Browses_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeClient) DeliverRecords(ctx context.Context, in *FindRecordsReq, opts ...grpc.CallOption) (*OperateResponse, error) {
	out := new(OperateResponse)
	err := c.cc.Invoke(ctx, Employee_DeliverRecords_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeClient) CompleteSelfInformation(ctx context.Context, in *SelfInformation, opts ...grpc.CallOption) (*comm.ResponseHeader, error) {
	out := new(comm.ResponseHeader)
	err := c.cc.Invoke(ctx, Employee_CompleteSelfInformation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeClient) FindEmployeeInformation(ctx context.Context, in *FindEmployeeInfoReq, opts ...grpc.CallOption) (*FindEmployeeResponse, error) {
	out := new(FindEmployeeResponse)
	err := c.cc.Invoke(ctx, Employee_FindEmployeeInformation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeClient) FindEmployeeSimpleInformation(ctx context.Context, in *SplitPage, opts ...grpc.CallOption) (*FindEmployeeSimpleResponse, error) {
	out := new(FindEmployeeSimpleResponse)
	err := c.cc.Invoke(ctx, Employee_FindEmployeeSimpleInformation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmployeeServer is the server API for Employee service.
// All implementations must embed UnimplementedEmployeeServer
// for forward compatibility
type EmployeeServer interface {
	Deliver(context.Context, *OperateRequest) (*OperateResponse, error)
	Browses(context.Context, *OperateRequest) (*OperateResponse, error)
	DeliverRecords(context.Context, *FindRecordsReq) (*OperateResponse, error)
	CompleteSelfInformation(context.Context, *SelfInformation) (*comm.ResponseHeader, error)
	FindEmployeeInformation(context.Context, *FindEmployeeInfoReq) (*FindEmployeeResponse, error)
	FindEmployeeSimpleInformation(context.Context, *SplitPage) (*FindEmployeeSimpleResponse, error)
	mustEmbedUnimplementedEmployeeServer()
}

// UnimplementedEmployeeServer must be embedded to have forward compatible implementations.
type UnimplementedEmployeeServer struct {
}

func (UnimplementedEmployeeServer) Deliver(context.Context, *OperateRequest) (*OperateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deliver not implemented")
}
func (UnimplementedEmployeeServer) Browses(context.Context, *OperateRequest) (*OperateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Browses not implemented")
}
func (UnimplementedEmployeeServer) DeliverRecords(context.Context, *FindRecordsReq) (*OperateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeliverRecords not implemented")
}
func (UnimplementedEmployeeServer) CompleteSelfInformation(context.Context, *SelfInformation) (*comm.ResponseHeader, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteSelfInformation not implemented")
}
func (UnimplementedEmployeeServer) FindEmployeeInformation(context.Context, *FindEmployeeInfoReq) (*FindEmployeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindEmployeeInformation not implemented")
}
func (UnimplementedEmployeeServer) FindEmployeeSimpleInformation(context.Context, *SplitPage) (*FindEmployeeSimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindEmployeeSimpleInformation not implemented")
}
func (UnimplementedEmployeeServer) mustEmbedUnimplementedEmployeeServer() {}

// UnsafeEmployeeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmployeeServer will
// result in compilation errors.
type UnsafeEmployeeServer interface {
	mustEmbedUnimplementedEmployeeServer()
}

func RegisterEmployeeServer(s grpc.ServiceRegistrar, srv EmployeeServer) {
	s.RegisterService(&Employee_ServiceDesc, srv)
}

func _Employee_Deliver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServer).Deliver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Employee_Deliver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServer).Deliver(ctx, req.(*OperateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Employee_Browses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServer).Browses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Employee_Browses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServer).Browses(ctx, req.(*OperateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Employee_DeliverRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRecordsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServer).DeliverRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Employee_DeliverRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServer).DeliverRecords(ctx, req.(*FindRecordsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Employee_CompleteSelfInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelfInformation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServer).CompleteSelfInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Employee_CompleteSelfInformation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServer).CompleteSelfInformation(ctx, req.(*SelfInformation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Employee_FindEmployeeInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindEmployeeInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServer).FindEmployeeInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Employee_FindEmployeeInformation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServer).FindEmployeeInformation(ctx, req.(*FindEmployeeInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Employee_FindEmployeeSimpleInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SplitPage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServer).FindEmployeeSimpleInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Employee_FindEmployeeSimpleInformation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServer).FindEmployeeSimpleInformation(ctx, req.(*SplitPage))
	}
	return interceptor(ctx, in, info, handler)
}

// Employee_ServiceDesc is the grpc.ServiceDesc for Employee service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Employee_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "employee.Employee",
	HandlerType: (*EmployeeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "deliver",
			Handler:    _Employee_Deliver_Handler,
		},
		{
			MethodName: "browses",
			Handler:    _Employee_Browses_Handler,
		},
		{
			MethodName: "deliverRecords",
			Handler:    _Employee_DeliverRecords_Handler,
		},
		{
			MethodName: "completeSelfInformation",
			Handler:    _Employee_CompleteSelfInformation_Handler,
		},
		{
			MethodName: "findEmployeeInformation",
			Handler:    _Employee_FindEmployeeInformation_Handler,
		},
		{
			MethodName: "findEmployeeSimpleInformation",
			Handler:    _Employee_FindEmployeeSimpleInformation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "employee/employee.proto",
}
