// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.24.2
// source: job/Job.proto

package job

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 错误码
type ResponseStatus int32

const (
	ResponseStatus_OK          ResponseStatus = 0
	ResponseStatus_InternalErr ResponseStatus = 1
)

// Enum value maps for ResponseStatus.
var (
	ResponseStatus_name = map[int32]string{
		0: "OK",
		1: "InternalErr",
	}
	ResponseStatus_value = map[string]int32{
		"OK":          0,
		"InternalErr": 1,
	}
)

func (x ResponseStatus) Enum() *ResponseStatus {
	p := new(ResponseStatus)
	*p = x
	return p
}

func (x ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_job_Job_proto_enumTypes[0].Descriptor()
}

func (ResponseStatus) Type() protoreflect.EnumType {
	return &file_job_Job_proto_enumTypes[0]
}

func (x ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseStatus.Descriptor instead.
func (ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_job_Job_proto_rawDescGZIP(), []int{0}
}

type FindJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Role  int32 `protobuf:"varint,2,opt,name=role,proto3" json:"role,omitempty"`
	ById  int32 `protobuf:"varint,3,opt,name=byId,proto3" json:"byId,omitempty"`
	Index int32 `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	Size  int32 `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *FindJobRequest) Reset() {
	*x = FindJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_Job_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindJobRequest) ProtoMessage() {}

func (x *FindJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_Job_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindJobRequest.ProtoReflect.Descriptor instead.
func (*FindJobRequest) Descriptor() ([]byte, []int) {
	return file_job_Job_proto_rawDescGZIP(), []int{0}
}

func (x *FindJobRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FindJobRequest) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *FindJobRequest) GetById() int32 {
	if x != nil {
		return x.ById
	}
	return 0
}

func (x *FindJobRequest) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *FindJobRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type FindJobByNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobName string `protobuf:"bytes,1,opt,name=jobName,proto3" json:"jobName,omitempty"`
}

func (x *FindJobByNameRequest) Reset() {
	*x = FindJobByNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_Job_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindJobByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindJobByNameRequest) ProtoMessage() {}

func (x *FindJobByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_Job_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindJobByNameRequest.ProtoReflect.Descriptor instead.
func (*FindJobByNameRequest) Descriptor() ([]byte, []int) {
	return file_job_Job_proto_rawDescGZIP(), []int{1}
}

func (x *FindJobByNameRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

type FindJobByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId string `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
}

func (x *FindJobByIdRequest) Reset() {
	*x = FindJobByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_Job_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindJobByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindJobByIdRequest) ProtoMessage() {}

func (x *FindJobByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_Job_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindJobByIdRequest.ProtoReflect.Descriptor instead.
func (*FindJobByIdRequest) Descriptor() ([]byte, []int) {
	return file_job_Job_proto_rawDescGZIP(), []int{2}
}

func (x *FindJobByIdRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type FindAllJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Size  int32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *FindAllJobRequest) Reset() {
	*x = FindAllJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_Job_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllJobRequest) ProtoMessage() {}

func (x *FindAllJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_job_Job_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllJobRequest.ProtoReflect.Descriptor instead.
func (*FindAllJobRequest) Descriptor() ([]byte, []int) {
	return file_job_Job_proto_rawDescGZIP(), []int{3}
}

func (x *FindAllJobRequest) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *FindAllJobRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type FindJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	JobMsg []*JobMessage   `protobuf:"bytes,2,rep,name=jobMsg,proto3" json:"jobMsg,omitempty"`
}

func (x *FindJobResponse) Reset() {
	*x = FindJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_Job_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindJobResponse) ProtoMessage() {}

func (x *FindJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_Job_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindJobResponse.ProtoReflect.Descriptor instead.
func (*FindJobResponse) Descriptor() ([]byte, []int) {
	return file_job_Job_proto_rawDescGZIP(), []int{4}
}

func (x *FindJobResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *FindJobResponse) GetJobMsg() []*JobMessage {
	if x != nil {
		return x.JobMsg
	}
	return nil
}

type SaveJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *SaveJobResponse) Reset() {
	*x = SaveJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_Job_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveJobResponse) ProtoMessage() {}

func (x *SaveJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_Job_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveJobResponse.ProtoReflect.Descriptor instead.
func (*SaveJobResponse) Descriptor() ([]byte, []int) {
	return file_job_Job_proto_rawDescGZIP(), []int{5}
}

func (x *SaveJobResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type ResponseHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  ResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=job.ResponseStatus" json:"status,omitempty"`
	Message string         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ResponseHeader) Reset() {
	*x = ResponseHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_Job_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHeader) ProtoMessage() {}

func (x *ResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_job_Job_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHeader.ProtoReflect.Descriptor instead.
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return file_job_Job_proto_rawDescGZIP(), []int{6}
}

func (x *ResponseHeader) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_OK
}

func (x *ResponseHeader) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RegisteredCompanyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Company *Company `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
}

func (x *RegisteredCompanyReq) Reset() {
	*x = RegisteredCompanyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_Job_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisteredCompanyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisteredCompanyReq) ProtoMessage() {}

func (x *RegisteredCompanyReq) ProtoReflect() protoreflect.Message {
	mi := &file_job_Job_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisteredCompanyReq.ProtoReflect.Descriptor instead.
func (*RegisteredCompanyReq) Descriptor() ([]byte, []int) {
	return file_job_Job_proto_rawDescGZIP(), []int{7}
}

func (x *RegisteredCompanyReq) GetCompany() *Company {
	if x != nil {
		return x.Company
	}
	return nil
}

type Company struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                          //id
	CompanyName     string `protobuf:"bytes,2,opt,name=companyName,proto3" json:"companyName,omitempty"`         //公司名称
	CompanyLocation string `protobuf:"bytes,3,opt,name=companyLocation,proto3" json:"companyLocation,omitempty"` //地址
	IsVip           int32  `protobuf:"varint,4,opt,name=isVip,proto3" json:"isVip,omitempty"`                    //是否会员
	IsCertified     int32  `protobuf:"varint,5,opt,name=isCertified,proto3" json:"isCertified,omitempty"`        //是否认证
	RegisterTime    int64  `protobuf:"varint,6,opt,name=registerTime,proto3" json:"registerTime,omitempty"`      //注册时间
	UpdateTime      int64  `protobuf:"varint,7,opt,name=updateTime,proto3" json:"updateTime,omitempty"`          //刷新时间
	Industry        string `protobuf:"bytes,8,opt,name=industry,proto3" json:"industry,omitempty"`               //行业
}

func (x *Company) Reset() {
	*x = Company{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_Job_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Company) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Company) ProtoMessage() {}

func (x *Company) ProtoReflect() protoreflect.Message {
	mi := &file_job_Job_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Company.ProtoReflect.Descriptor instead.
func (*Company) Descriptor() ([]byte, []int) {
	return file_job_Job_proto_rawDescGZIP(), []int{8}
}

func (x *Company) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Company) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *Company) GetCompanyLocation() string {
	if x != nil {
		return x.CompanyLocation
	}
	return ""
}

func (x *Company) GetIsVip() int32 {
	if x != nil {
		return x.IsVip
	}
	return 0
}

func (x *Company) GetIsCertified() int32 {
	if x != nil {
		return x.IsCertified
	}
	return 0
}

func (x *Company) GetRegisterTime() int64 {
	if x != nil {
		return x.RegisterTime
	}
	return 0
}

func (x *Company) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *Company) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

type BoundCompanyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *BoundCompanyReq) Reset() {
	*x = BoundCompanyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_Job_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoundCompanyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundCompanyReq) ProtoMessage() {}

func (x *BoundCompanyReq) ProtoReflect() protoreflect.Message {
	mi := &file_job_Job_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundCompanyReq.ProtoReflect.Descriptor instead.
func (*BoundCompanyReq) Descriptor() ([]byte, []int) {
	return file_job_Job_proto_rawDescGZIP(), []int{9}
}

func (x *BoundCompanyReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type VerifyCompanyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *VerifyCompanyReq) Reset() {
	*x = VerifyCompanyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_Job_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyCompanyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCompanyReq) ProtoMessage() {}

func (x *VerifyCompanyReq) ProtoReflect() protoreflect.Message {
	mi := &file_job_Job_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCompanyReq.ProtoReflect.Descriptor instead.
func (*VerifyCompanyReq) Descriptor() ([]byte, []int) {
	return file_job_Job_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyCompanyReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CommonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_Job_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_job_Job_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_job_Job_proto_rawDescGZIP(), []int{11}
}

func (x *CommonResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type JobMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId          int32  `protobuf:"varint,2,opt,name=jobId,proto3" json:"jobId,omitempty"`                  //职位id
	JobName        string `protobuf:"bytes,3,opt,name=jobName,proto3" json:"jobName,omitempty"`               //职位名称
	JobMoney       int32  `protobuf:"varint,4,opt,name=jobMoney,proto3" json:"jobMoney,omitempty"`            //薪资
	JobReq         string `protobuf:"bytes,5,opt,name=jobReq,proto3" json:"jobReq,omitempty"`                 //职位要求
	JobLocation    string `protobuf:"bytes,6,opt,name=jobLocation,proto3" json:"jobLocation,omitempty"`       //职位地址
	CompanyId      int32  `protobuf:"varint,7,opt,name=companyId,proto3" json:"companyId,omitempty"`          //公司id(用户id)
	RecruiterName  string `protobuf:"bytes,8,opt,name=recruiterName,proto3" json:"recruiterName,omitempty"`   //招聘者
	RecruiterPhone string `protobuf:"bytes,9,opt,name=recruiterPhone,proto3" json:"recruiterPhone,omitempty"` //招聘者手机号
	JobNeed        int32  `protobuf:"varint,10,opt,name=jobNeed,proto3" json:"jobNeed,omitempty"`             //招聘人数
	RecruiterId    int32  `protobuf:"varint,11,opt,name=recruiterId,proto3" json:"recruiterId,omitempty"`     //招聘者id
	OpenTime       int64  `protobuf:"varint,12,opt,name=openTime,proto3" json:"openTime,omitempty"`           //职位发布时间
	JobTags        string `protobuf:"bytes,13,opt,name=jobTags,proto3" json:"jobTags,omitempty"`              //职位标签
	UpdateTime     int64  `protobuf:"varint,14,opt,name=updateTime,proto3" json:"updateTime,omitempty"`       //职位刷新时间
	Industry       string `protobuf:"bytes,15,opt,name=industry,proto3" json:"industry,omitempty"`            //行业
}

func (x *JobMessage) Reset() {
	*x = JobMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_job_Job_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobMessage) ProtoMessage() {}

func (x *JobMessage) ProtoReflect() protoreflect.Message {
	mi := &file_job_Job_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobMessage.ProtoReflect.Descriptor instead.
func (*JobMessage) Descriptor() ([]byte, []int) {
	return file_job_Job_proto_rawDescGZIP(), []int{12}
}

func (x *JobMessage) GetJobId() int32 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *JobMessage) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *JobMessage) GetJobMoney() int32 {
	if x != nil {
		return x.JobMoney
	}
	return 0
}

func (x *JobMessage) GetJobReq() string {
	if x != nil {
		return x.JobReq
	}
	return ""
}

func (x *JobMessage) GetJobLocation() string {
	if x != nil {
		return x.JobLocation
	}
	return ""
}

func (x *JobMessage) GetCompanyId() int32 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *JobMessage) GetRecruiterName() string {
	if x != nil {
		return x.RecruiterName
	}
	return ""
}

func (x *JobMessage) GetRecruiterPhone() string {
	if x != nil {
		return x.RecruiterPhone
	}
	return ""
}

func (x *JobMessage) GetJobNeed() int32 {
	if x != nil {
		return x.JobNeed
	}
	return 0
}

func (x *JobMessage) GetRecruiterId() int32 {
	if x != nil {
		return x.RecruiterId
	}
	return 0
}

func (x *JobMessage) GetOpenTime() int64 {
	if x != nil {
		return x.OpenTime
	}
	return 0
}

func (x *JobMessage) GetJobTags() string {
	if x != nil {
		return x.JobTags
	}
	return ""
}

func (x *JobMessage) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *JobMessage) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

var File_job_Job_proto protoreflect.FileDescriptor

var file_job_Job_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6a, 0x6f, 0x62, 0x2f, 0x4a, 0x6f, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x6a, 0x6f, 0x62, 0x22, 0x72, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x64, 0x4a, 0x6f, 0x62, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x79,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x62, 0x79, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x30, 0x0a, 0x14, 0x46, 0x69, 0x6e, 0x64,
	0x4a, 0x6f, 0x62, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x6a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2a, 0x0a, 0x12, 0x46, 0x69,
	0x6e, 0x64, 0x4a, 0x6f, 0x62, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x11, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c,
	0x6c, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x67, 0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x64, 0x4a, 0x6f, 0x62,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x4d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x4a, 0x6f, 0x62, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x06, 0x6a, 0x6f, 0x62, 0x4d, 0x73, 0x67, 0x22, 0x3e,
	0x0a, 0x0f, 0x53, 0x61, 0x76, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2b, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x57,
	0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x13, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3e, 0x0a, 0x14, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x65, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x12,
	0x26, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x07,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x22, 0xfd, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x70,
	0x61, 0x6e, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x73, 0x56, 0x69, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x69, 0x73, 0x56, 0x69, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x73, 0x43, 0x65, 0x72, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x69, 0x73, 0x43, 0x65,
	0x72, 0x74, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69,
	0x6e, 0x64, 0x75, 0x73, 0x74, 0x72, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69,
	0x6e, 0x64, 0x75, 0x73, 0x74, 0x72, 0x79, 0x22, 0x21, 0x0a, 0x0f, 0x42, 0x6f, 0x75, 0x6e, 0x64,
	0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x22, 0x0a, 0x10, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3d,
	0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2b, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0xac, 0x03,
	0x0a, 0x0a, 0x4a, 0x6f, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6a, 0x6f, 0x62, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6a, 0x6f, 0x62,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x6a, 0x6f, 0x62, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x6a, 0x6f, 0x62, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x52,
	0x65, 0x71, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6a, 0x6f, 0x62, 0x52, 0x65, 0x71,
	0x12, 0x20, 0x0a, 0x0b, 0x6a, 0x6f, 0x62, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6a, 0x6f, 0x62, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x64, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x64,
	0x12, 0x24, 0x0a, 0x0d, 0x72, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x72, 0x65, 0x63, 0x72, 0x75, 0x69,
	0x74, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x72, 0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x65, 0x72, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6a, 0x6f, 0x62, 0x4e, 0x65, 0x65, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x6a, 0x6f, 0x62, 0x4e, 0x65, 0x65, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x72,
	0x75, 0x69, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x72,
	0x65, 0x63, 0x72, 0x75, 0x69, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70,
	0x65, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6f, 0x70,
	0x65, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6a, 0x6f, 0x62, 0x54, 0x61, 0x67,
	0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6a, 0x6f, 0x62, 0x54, 0x61, 0x67, 0x73,
	0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0e,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x64, 0x75, 0x73, 0x74, 0x72, 0x79, 0x18, 0x0f, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x64, 0x75, 0x73, 0x74, 0x72, 0x79, 0x2a, 0x29, 0x0a, 0x0e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06,
	0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x45, 0x72, 0x72, 0x10, 0x01, 0x32, 0xf3, 0x04, 0x0a, 0x03, 0x4a, 0x6f, 0x62, 0x12,
	0x3d, 0x0a, 0x0b, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x4a, 0x6f, 0x62, 0x73, 0x12, 0x16,
	0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x4a, 0x6f, 0x62, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x46, 0x69, 0x6e,
	0x64, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42,
	0x0a, 0x0d, 0x46, 0x69, 0x6e, 0x64, 0x4a, 0x6f, 0x62, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x19, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4a, 0x6f, 0x62, 0x42, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6a, 0x6f, 0x62,
	0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0b, 0x46, 0x69, 0x6e, 0x64, 0x4a, 0x6f, 0x62, 0x42, 0x79, 0x49,
	0x64, 0x12, 0x17, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4a, 0x6f, 0x62, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6a, 0x6f, 0x62,
	0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x37, 0x0a, 0x08, 0x46, 0x69, 0x6e, 0x64, 0x4a, 0x6f, 0x62, 0x73, 0x12, 0x13,
	0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4a, 0x6f,
	0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x08, 0x53,
	0x61, 0x76, 0x65, 0x4a, 0x6f, 0x62, 0x73, 0x12, 0x0f, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x4a, 0x6f,
	0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x14, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x53,
	0x61, 0x76, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x35, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4a, 0x6f, 0x62, 0x73, 0x12, 0x0f,
	0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x4a, 0x6f, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a,
	0x14, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x11, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x65, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12, 0x19, 0x2e, 0x6a,
	0x6f, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x43, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41,
	0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12,
	0x19, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64,
	0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x6a, 0x6f, 0x62,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x3b, 0x0a, 0x0c, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x79, 0x12, 0x14, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x43, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d,
	0x0a, 0x0d, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12,
	0x15, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x6d, 0x70,
	0x61, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x19, 0x0a,
	0x0e, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x70, 0x74, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x05, 0x2e, 0x2f, 0x6a, 0x6f, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_job_Job_proto_rawDescOnce sync.Once
	file_job_Job_proto_rawDescData = file_job_Job_proto_rawDesc
)

func file_job_Job_proto_rawDescGZIP() []byte {
	file_job_Job_proto_rawDescOnce.Do(func() {
		file_job_Job_proto_rawDescData = protoimpl.X.CompressGZIP(file_job_Job_proto_rawDescData)
	})
	return file_job_Job_proto_rawDescData
}

var file_job_Job_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_job_Job_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_job_Job_proto_goTypes = []interface{}{
	(ResponseStatus)(0),          // 0: job.ResponseStatus
	(*FindJobRequest)(nil),       // 1: job.FindJobRequest
	(*FindJobByNameRequest)(nil), // 2: job.FindJobByNameRequest
	(*FindJobByIdRequest)(nil),   // 3: job.FindJobByIdRequest
	(*FindAllJobRequest)(nil),    // 4: job.FindAllJobRequest
	(*FindJobResponse)(nil),      // 5: job.FindJobResponse
	(*SaveJobResponse)(nil),      // 6: job.SaveJobResponse
	(*ResponseHeader)(nil),       // 7: job.ResponseHeader
	(*RegisteredCompanyReq)(nil), // 8: job.RegisteredCompanyReq
	(*Company)(nil),              // 9: job.Company
	(*BoundCompanyReq)(nil),      // 10: job.BoundCompanyReq
	(*VerifyCompanyReq)(nil),     // 11: job.VerifyCompanyReq
	(*CommonResponse)(nil),       // 12: job.CommonResponse
	(*JobMessage)(nil),           // 13: job.JobMessage
}
var file_job_Job_proto_depIdxs = []int32{
	7,  // 0: job.FindJobResponse.header:type_name -> job.ResponseHeader
	13, // 1: job.FindJobResponse.jobMsg:type_name -> job.JobMessage
	7,  // 2: job.SaveJobResponse.header:type_name -> job.ResponseHeader
	0,  // 3: job.ResponseHeader.status:type_name -> job.ResponseStatus
	9,  // 4: job.RegisteredCompanyReq.company:type_name -> job.Company
	7,  // 5: job.CommonResponse.header:type_name -> job.ResponseHeader
	4,  // 6: job.Job.FindAllJobs:input_type -> job.FindAllJobRequest
	2,  // 7: job.Job.FindJobByName:input_type -> job.FindJobByNameRequest
	3,  // 8: job.Job.FindJobById:input_type -> job.FindJobByIdRequest
	1,  // 9: job.Job.FindJobs:input_type -> job.FindJobRequest
	13, // 10: job.Job.SaveJobs:input_type -> job.JobMessage
	13, // 11: job.Job.UpdateJobs:input_type -> job.JobMessage
	8,  // 12: job.Job.RegisteredCompany:input_type -> job.RegisteredCompanyReq
	8,  // 13: job.Job.UpdateCompany:input_type -> job.RegisteredCompanyReq
	10, // 14: job.Job.BoundCompany:input_type -> job.BoundCompanyReq
	11, // 15: job.Job.VerifyCompany:input_type -> job.VerifyCompanyReq
	5,  // 16: job.Job.FindAllJobs:output_type -> job.FindJobResponse
	5,  // 17: job.Job.FindJobByName:output_type -> job.FindJobResponse
	5,  // 18: job.Job.FindJobById:output_type -> job.FindJobResponse
	5,  // 19: job.Job.FindJobs:output_type -> job.FindJobResponse
	6,  // 20: job.Job.SaveJobs:output_type -> job.SaveJobResponse
	6,  // 21: job.Job.UpdateJobs:output_type -> job.SaveJobResponse
	12, // 22: job.Job.RegisteredCompany:output_type -> job.CommonResponse
	12, // 23: job.Job.UpdateCompany:output_type -> job.CommonResponse
	12, // 24: job.Job.BoundCompany:output_type -> job.CommonResponse
	12, // 25: job.Job.VerifyCompany:output_type -> job.CommonResponse
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_job_Job_proto_init() }
func file_job_Job_proto_init() {
	if File_job_Job_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_job_Job_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_Job_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindJobByNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_Job_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindJobByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_Job_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_Job_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_Job_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_Job_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_Job_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisteredCompanyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_Job_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Company); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_Job_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoundCompanyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_Job_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyCompanyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_Job_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_job_Job_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_job_Job_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_job_Job_proto_goTypes,
		DependencyIndexes: file_job_Job_proto_depIdxs,
		EnumInfos:         file_job_Job_proto_enumTypes,
		MessageInfos:      file_job_Job_proto_msgTypes,
	}.Build()
	File_job_Job_proto = out.File
	file_job_Job_proto_rawDesc = nil
	file_job_Job_proto_goTypes = nil
	file_job_Job_proto_depIdxs = nil
}
